languageCode = "en-us"
relativeURLs = true
sourceRelativeLinksEval = true
ignoreFiles = [ "\\.less$" ]
sectionPagesMenu = "main"
googleAnalytics = "UA-96910779-7"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[params]
  # baseurl = "https://cluster.ipfs.io"
  name = "IPFS CLUSTER"
  title = "IPFS CLUSTER"
  description = "Pinset orchestration for IPFS"
  author = "Protocol Labs"
  github = "https://github.com/ipfs/ipfs-cluster"
  domain = "cluster.ipfs.io"
  og_image = "https://cluster.ipfs.io/og-image.jpg"
  download = "https://dist.ipfs.io/#ipfs-cluster-service"
