languageCode = "en-us"
relativeURLs = true
sourceRelativeLinksEval = true

[params]
  baseurl = "https://cluster.ipfs.io"
  name = "IPFS Cluster"
  title = "IPFS Cluster"
  description = "Collective pinning and composition for IPFS"
  author = "Protocol Labs"
  github = "https://github.com/ipfs/ipfs-cluster"
  domain = "cluster.ipfs.io"
  og_image = "https://cluster.ipfs.io/og-image.jpg"
  download = "https://dist.ipfs.io/#ipfs-cluster-service"